### ISSUE TITLE
Bind to lifecycle phase

### ISSUE THREAD

**Issue by redcatbear** [itsallcode/openfasttrace-maven-plugin#6]
## Situation

Currently the plugin is not automatically executed in any lifecycle phase. In my opinion this would help though.

Potential candidates:

* `validate`: executed before compilation (i.e. before unit and integration tests)
* `verify`: executed after integration tests

### Considered alternatives

Executing it before the tests means that you get fast feedback on broken traces. This is especially handy in case of long-running integration tests.

On the other hand those checks are in the way if you just want to quickly run your unit tests. I usually do this through the IDE, but a lot of people use Maven for this job.

All in all `verify` is the less invasive choice for a default setting.

## Acceptance Criteria

1. Users can choose between running OFT in the phase `validate` or `verify`
2. By default OFT runs in phase `verify`

## See Also

https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Lifecycle_Reference

**Comment by kaklakariada** [comment]
The trace mojo is already associated with the verify lifecycle: https://github.com/itsallcode/openfasttrace-maven-plugin/blob/develop/src/main/java/org/itsallcode/openfasttrace/maven/TraceMojo.java#L54

I didn't find a way to verify this in an integration test. Can you please check if it already works?

**Comment by kaklakariada** [comment]
Already implemented in a3a8609988c90d25d85f6f35ecb5ecfa97e66d2c
Waiting for confirmation that it works.

**Comment by kaklakariada** [comment]
I verified that oft is executed when running `mvn verify`. See #13.
